# Generated by Django 5.2.5 on 2025-08-30 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_processing', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprocessingjob',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiprocessingjob',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_processing_jobs', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='aiprocessinglog',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ai_processing.aiprocessingjob'),
        ),
        migrations.AddField(
            model_name='aiprocessinglog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_processing_logs', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='document',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenants.company'),
        ),
        migrations.AddField(
            model_name='document',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiprocessinglog',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='ai_processing.document'),
        ),
        migrations.AddField(
            model_name='aiprocessingjob',
            name='documents',
            field=models.ManyToManyField(related_name='processing_jobs', to='ai_processing.document'),
        ),
        migrations.AddField(
            model_name='aiextractionresult',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_results', to='ai_processing.document'),
        ),
        migrations.AddField(
            model_name='aicategorization',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorizations', to='ai_processing.document'),
        ),
    ]
