# Generated by Django 5.2.6 on 2025-09-26 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_item_sku'),
        ('purchase', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='receipt_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('tenant', 'order_number'), name='uniq_tenant_purchase_order_number'),
        ),
        migrations.AddConstraint(
            model_name='purchasereceipt',
            constraint=models.UniqueConstraint(fields=('tenant', 'receipt_number'), name='uniq_tenant_receipt_number'),
        ),
    ]
