# Generated by Django 5.2.6 on 2025-12-08 16:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0007_rename_e_invoice__invoice_8a3f2d_idx_e_invoice_s_invoice_d1d296_idx_and_more'),
        ('purchase', '0003_purchaseorderline_created_by_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(max_length=255)),
                ('network', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('block_reason', models.CharField(choices=[('unknown_address', 'Unknown Wallet Address'), ('suspicious_pattern', 'Suspicious Transaction Pattern'), ('no_transaction_history', 'No Transaction History'), ('risk_score_threshold', 'High Risk Score'), ('manual_block', 'Manually Blocked')], max_length=50)),
                ('risk_factors', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('blocked', 'Blocked'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('resolved', 'Resolved')], default='blocked', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_payments', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_blocks', to='invoicing.invoice')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_blocks', to='purchase.purchaseorder')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_payments', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_blocks', to='purchase.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_blocks', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payment Block',
                'verbose_name_plural': 'Payment Blocks',
                'db_table': 'payment_blocks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['supplier', 'status'], name='payment_blo_supplie_56bbb3_idx'), models.Index(fields=['wallet_address', 'network'], name='payment_blo_wallet__7b31f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='VendorVerificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(max_length=255)),
                ('network', models.CharField(max_length=50)),
                ('verification_type', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual'), ('payment_check', 'Payment Check'), ('transaction_analysis', 'Transaction Analysis')], max_length=50)),
                ('verification_status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('warning', 'Warning'), ('blocked', 'Blocked')], max_length=20)),
                ('risk_factors', models.JSONField(blank=True, default=list, help_text='List of risk factors identified')),
                ('transaction_history_match', models.BooleanField(default=False)),
                ('address_found_in_history', models.BooleanField(default=False)),
                ('transaction_count_found', models.IntegerField(default=0)),
                ('recommendation', models.CharField(choices=[('approve', 'Approve'), ('review', 'Review Required'), ('block', 'Block Payment')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='purchase.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='tenants.tenant')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Verification Log',
                'verbose_name_plural': 'Vendor Verification Logs',
                'db_table': 'vendor_verification_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['supplier', 'verification_status'], name='vendor_veri_supplie_1170a0_idx'), models.Index(fields=['wallet_address', 'network'], name='vendor_veri_wallet__928108_idx')],
            },
        ),
        migrations.CreateModel(
            name='VendorWalletAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(help_text='Cryptocurrency wallet address', max_length=255)),
                ('network', models.CharField(choices=[('ethereum', 'Ethereum'), ('polygon', 'Polygon'), ('bsc', 'Binance Smart Chain'), ('solana', 'Solana'), ('arbitrum', 'Arbitrum'), ('optimism', 'Optimism'), ('base', 'Base')], max_length=50)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary wallet address for this supplier')),
                ('is_verified', models.BooleanField(default=False, help_text='Manually verified by admin')),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('transaction_count', models.IntegerField(default=0, help_text='Number of transactions from this address')),
                ('first_transaction_date', models.DateTimeField(blank=True, null=True)),
                ('last_transaction_date', models.DateTimeField(blank=True, null=True)),
                ('total_amount_received', models.DecimalField(decimal_places=18, default=0, max_digits=30)),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, help_text='Risk score 0-100', max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_addresses', to='purchase.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_wallets', to='tenants.tenant')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Wallet Address',
                'verbose_name_plural': 'Vendor Wallet Addresses',
                'db_table': 'vendor_wallet_addresses',
                'indexes': [models.Index(fields=['supplier', 'is_primary'], name='vendor_wall_supplie_11cb43_idx'), models.Index(fields=['is_verified', 'risk_score'], name='vendor_wall_is_veri_1287cd_idx')],
                'unique_together': {('tenant', 'wallet_address', 'network')},
            },
        ),
    ]
