# Generated by Django 5.2.6 on 2025-12-23 08:16

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryvaluation_inventorysettings'),
        ('purchase', '0004_paymentblock_vendorverificationlog_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_type', models.CharField(choices=[('purchase_order', 'Purchase Order'), ('receipt', 'Receipt'), ('payment', 'Payment'), ('contract', 'Contract')], default='purchase_order', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approval_level', models.IntegerField(default=1, help_text='Approval level in workflow')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_requests', to=settings.AUTH_USER_MODEL)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_approvals_to_approve', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='purchase.purchaseorder')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_purchase_approvals', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_approval_requests', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Purchase Approval Request',
                'verbose_name_plural': 'Purchase Approval Requests',
                'db_table': 'purchase_approval_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('contract_type', models.CharField(choices=[('master_agreement', 'Master Agreement'), ('purchase_agreement', 'Purchase Agreement'), ('service_agreement', 'Service Agreement'), ('framework_agreement', 'Framework Agreement'), ('blanket_order', 'Blanket Order'), ('other', 'Other')], default='purchase_agreement', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('renewed', 'Renewed')], default='draft', max_length=20)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_terms', models.CharField(default='net_30', max_length=50)),
                ('renewal_option', models.BooleanField(default=False)),
                ('auto_renew', models.BooleanField(default=False)),
                ('renewal_notice_days', models.IntegerField(default=30)),
                ('document_url', models.URLField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('terms_conditions', models.TextField(blank=True)),
                ('signed_by_supplier', models.BooleanField(default=False)),
                ('signed_by_company', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_contracts', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_contracts', to='tenants.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_purchase_contracts', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='purchase.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_contracts', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Purchase Contract',
                'verbose_name_plural': 'Purchase Contracts',
                'db_table': 'purchase_contracts',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'contract_number')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('default_payment_terms', models.CharField(choices=[('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_60', 'Net 60'), ('net_90', 'Net 90'), ('due_on_receipt', 'Due on Receipt')], default='net_30', max_length=50)),
                ('order_number_prefix', models.CharField(default='PO-', max_length=20)),
                ('order_number_format', models.CharField(default='{prefix}{year}-{number:04d}', max_length=50)),
                ('require_order_approval', models.BooleanField(default=False)),
                ('require_receipt_approval', models.BooleanField(default=False)),
                ('approval_threshold', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Amount threshold requiring approval', max_digits=15)),
                ('enable_receiving_inspection', models.BooleanField(default=True)),
                ('enable_contract_management', models.BooleanField(default=True)),
                ('default_contract_validity_days', models.IntegerField(default=365)),
                ('auto_renewal_reminder_days', models.IntegerField(default=30)),
                ('enable_purchase_analytics', models.BooleanField(default=True)),
                ('analytics_retention_days', models.IntegerField(default=365)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_settings', to='tenants.company')),
                ('default_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_purchase_settings', to='inventory.warehouse')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_settings', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Purchase Settings',
                'verbose_name_plural': 'Purchase Settings',
                'db_table': 'purchase_settings',
                'unique_together': {('tenant', 'company')},
            },
        ),
    ]
