# Generated by Django 5.2.6 on 2025-12-26 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_purchaseapprovalrequest_purchasecontract_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='converted_amount_in_base_currency',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted to tenant base currency', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='data_classification',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted'), ('top_secret', 'Top Secret')], default='confidential', help_text='Data classification level', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='exchange_rate_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when exchange rate was applied', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_sensitive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='requires_audit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='retention_period_days',
            field=models.PositiveIntegerField(default=2555),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='transaction_currency',
            field=models.CharField(blank=True, help_text='Currency code for this transaction (e.g., USD, MYR)', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
