# Generated by Django 5.2.6 on 2026-01-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentstorage',
            name='storage_type',
            field=models.CharField(choices=[('local', 'Local Storage'), ('s3', 'AWS S3'), ('r2', 'Cloudflare R2'), ('azure', 'Azure Blob Storage'), ('gcs', 'Google Cloud Storage'), ('dropbox', 'Dropbox'), ('onedrive', 'OneDrive'), ('custom', 'Custom Storage')], max_length=50),
        ),
    ]
