# Generated by Django 4.2.24 on 2025-09-25 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('inquiry_type', models.CharField(choices=[('demo', 'Request Demo'), ('pricing', 'Pricing Information'), ('enterprise', 'Enterprise Solution'), ('partnership', 'Partnership Inquiry'), ('support', 'Technical Support'), ('general', 'General Information')], default='general', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('company_size', models.CharField(blank=True, max_length=50, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('current_solution', models.CharField(blank=True, max_length=200, null=True)),
                ('budget_range', models.CharField(blank=True, max_length=50, null=True)),
                ('timeline', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('demo_scheduled', 'Demo Scheduled'), ('proposal_sent', 'Proposal Sent'), ('negotiating', 'Negotiating'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost'), ('follow_up', 'Follow Up Required')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('source', models.CharField(default='website', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inquiries', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_inquiries', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Sales Inquiry',
                'verbose_name_plural': 'Sales Inquiries',
                'db_table': 'sales_inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesInquiryResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response_type', models.CharField(choices=[('email', 'Email'), ('call', 'Phone Call'), ('meeting', 'Meeting'), ('demo', 'Demo'), ('proposal', 'Proposal'), ('follow_up', 'Follow Up')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='contact_sales.salesinquiry')),
                ('responded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Inquiry Response',
                'verbose_name_plural': 'Sales Inquiry Responses',
                'db_table': 'sales_inquiry_responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesInquiryAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField()),
                ('file_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='contact_sales.salesinquiry')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Inquiry Attachment',
                'verbose_name_plural': 'Sales Inquiry Attachments',
                'db_table': 'sales_inquiry_attachments',
            },
        ),
    ]
