# Generated by Django 5.2.5 on 2025-08-30 15:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('routing_number', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('money_market', 'Money Market'), ('credit_card', 'Credit Card'), ('line_of_credit', 'Line of Credit')], max_length=50)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('last_reconciliation_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='tenants.company')),
                ('gl_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.chartofaccounts')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'db_table': 'bank_accounts',
                'unique_together': {('tenant', 'company', 'account_number')},
            },
        ),
        migrations.CreateModel(
            name='BankIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=255)),
                ('integration_type', models.CharField(choices=[('plaid', 'Plaid'), ('yodlee', 'Yodlee'), ('teller', 'Teller'), ('manual', 'Manual')], max_length=50)),
                ('provider', models.CharField(choices=[('plaid', 'Plaid'), ('yodlee', 'Yodlee'), ('teller', 'Teller'), ('manual', 'Manual')], max_length=50)),
                ('last_sync_date', models.DateTimeField(blank=True, null=True)),
                ('endpoint_url', models.URLField(blank=True)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('api_secret', models.CharField(blank=True, max_length=255)),
                ('access_token', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_integrations', to='banking.bankaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_integrations', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Bank Integration',
                'verbose_name_plural': 'Bank Integrations',
                'db_table': 'bank_integrations',
            },
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement_date', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='banking.bankaccount')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Statement',
                'verbose_name_plural': 'Bank Statements',
                'db_table': 'bank_statements',
                'ordering': ['-statement_date'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('fee', 'Fee'), ('interest', 'Interest')], max_length=20)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('fee', 'Fee'), ('interest', 'Interest')], max_length=50)),
                ('reconciliation_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('reconciliation_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.bankaccount')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'Bank Transaction',
                'verbose_name_plural': 'Bank Transactions',
                'db_table': 'bank_transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
