# Generated by Django 5.2.6 on 2025-12-08 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
    ]
