# Generated by Django 5.2.6 on 2025-12-09 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_auto_20251208_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.bankaccount'),
        ),
    ]
