# Generated by Django 5.2.6 on 2025-12-23 08:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_add_bank_account_to_transaction'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='bank_account',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_statements', to='banking.bankaccount'),
        ),
        migrations.CreateModel(
            name='ImportExportJob',
            fields=[
                ('data_classification', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted'), ('top_secret', 'Top Secret')], default='confidential', help_text='Data classification level', max_length=20)),
                ('requires_audit', models.BooleanField(default=True)),
                ('retention_period_days', models.PositiveIntegerField(default=2555)),
                ('is_sensitive', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('import', 'Import'), ('export', 'Export')], max_length=20)),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('ofx', 'OFX'), ('qif', 'QIF'), ('json', 'JSON')], max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_records', models.IntegerField(default=0)),
                ('processed_records', models.IntegerField(default=0)),
                ('failed_records', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_export_jobs', to='banking.bankaccount')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_export_jobs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_export_jobs', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import/Export Job',
                'verbose_name_plural': 'Import/Export Jobs',
                'db_table': 'import_export_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankingSettings',
            fields=[
                ('data_classification', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted'), ('top_secret', 'Top Secret')], default='confidential', help_text='Data classification level', max_length=20)),
                ('requires_audit', models.BooleanField(default=True)),
                ('retention_period_days', models.PositiveIntegerField(default=2555)),
                ('is_sensitive', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('auto_reconcile', models.BooleanField(default=False)),
                ('auto_reconcile_days', models.IntegerField(default=30, help_text='Days to auto-reconcile transactions')),
                ('enable_plaid', models.BooleanField(default=False)),
                ('enable_auto_sync', models.BooleanField(default=True)),
                ('sync_frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('manual', 'Manual')], default='daily', max_length=20)),
                ('require_approval_for_large_transactions', models.BooleanField(default=True)),
                ('large_transaction_threshold', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=15)),
                ('enable_transaction_alerts', models.BooleanField(default=True)),
                ('notify_on_reconciliation', models.BooleanField(default=True)),
                ('notify_on_sync_error', models.BooleanField(default=True)),
                ('notify_on_large_transaction', models.BooleanField(default=True)),
                ('default_export_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('json', 'JSON')], default='csv', max_length=20)),
                ('auto_delete_old_exports', models.BooleanField(default=False)),
                ('export_retention_days', models.IntegerField(default=90)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banking_settings', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banking_settings', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Banking Settings',
                'verbose_name_plural': 'Banking Settings',
                'db_table': 'banking_settings',
                'unique_together': {('tenant', 'company')},
            },
        ),
        migrations.CreateModel(
            name='PlaidConnection',
            fields=[
                ('data_classification', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted'), ('top_secret', 'Top Secret')], default='confidential', help_text='Data classification level', max_length=20)),
                ('requires_audit', models.BooleanField(default=True)),
                ('retention_period_days', models.PositiveIntegerField(default=2555)),
                ('is_sensitive', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_id', models.CharField(help_text='Plaid Item ID', max_length=255)),
                ('access_token', models.CharField(help_text='Encrypted Plaid access token', max_length=500)),
                ('institution_id', models.CharField(blank=True, max_length=255)),
                ('institution_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('error', 'Error'), ('disconnected', 'Disconnected')], default='active', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('last_successful_sync', models.DateTimeField(blank=True, null=True)),
                ('last_failed_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plaid_connections', to='banking.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plaid_connections', to='banking.bankintegration')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plaid_connections', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plaid Connection',
                'verbose_name_plural': 'Plaid Connections',
                'db_table': 'plaid_connections',
                'ordering': ['-created_at'],
                'unique_together': {('tenant', 'item_id')},
            },
        ),
    ]
