# Generated by Django 5.2.6 on 2025-12-23 08:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_bankstatement_bank_account_importexportjob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='bank_account',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_statements', to='banking.bankaccount'),
        ),
    ]
