# Generated by Django 5.2.6 on 2025-12-25 07:48

from django.db import migrations


def add_bank_account_column_if_missing(apps, schema_editor):
    """Add bank_account_id column if it doesn't exist"""
    connection = schema_editor.connection
    cursor = connection.cursor()
    try:
        # Check if column exists using matching introspection method
        description = connection.introspection.get_table_description(cursor, 'bank_transactions')
        columns = [col.name for col in description]
        
        if 'bank_account_id' not in columns:
            # Add the column manually
            # Note: For SQLite compatibility we might need care, but assuming generic SQL works for now
            # or relying on Django to handle the type if we used AddField.
            # Since strict SQL is used:
            cursor.execute("""
                ALTER TABLE bank_transactions 
                ADD COLUMN bank_account_id UUID REFERENCES bank_accounts(id) ON DELETE CASCADE
            """)
    finally:
        cursor.close()


def remove_bank_account_column_if_exists(apps, schema_editor):
    """Remove bank_account_id column if it exists (reverse migration)"""
    connection = schema_editor.connection
    cursor = connection.cursor()
    try:
        description = connection.introspection.get_table_description(cursor, 'bank_transactions')
        columns = [col.name for col in description]
        
        if 'bank_account_id' in columns:
            # Remove the column
            if connection.vendor == 'sqlite':
                 # SQLite does not support DROP COLUMN in older versions, but Django's sqlite backend might?
                 # Raw SQL DROP COLUMN is supported in newer SQLite.
                 cursor.execute("ALTER TABLE bank_transactions DROP COLUMN bank_account_id")
            else:
                 cursor.execute("""
                    ALTER TABLE bank_transactions 
                    DROP COLUMN bank_account_id
                """)
    finally:
        cursor.close()


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_alter_bankstatement_bank_account'),
    ]

    operations = [
        migrations.RunPython(
            add_bank_account_column_if_missing,
            reverse_code=remove_bank_account_column_if_exists
        ),
    ]
