# Generated by Django 5.2.6 on 2025-12-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_fix_bank_account_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='converted_amount_in_base_currency',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted to tenant base currency', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Exchange rate used for conversion (from transaction_currency to base_currency)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='exchange_rate_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when exchange rate was applied', null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='transaction_currency',
            field=models.CharField(blank=True, help_text='Currency code for this transaction (e.g., USD, MYR)', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='bankingsettings',
            name='converted_amount_in_base_currency',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted to tenant base currency', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='bankingsettings',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Exchange rate used for conversion (from transaction_currency to base_currency)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='bankingsettings',
            name='exchange_rate_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when exchange rate was applied', null=True),
        ),
        migrations.AddField(
            model_name='bankingsettings',
            name='transaction_currency',
            field=models.CharField(blank=True, help_text='Currency code for this transaction (e.g., USD, MYR)', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='bankintegration',
            name='converted_amount_in_base_currency',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted to tenant base currency', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='bankintegration',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Exchange rate used for conversion (from transaction_currency to base_currency)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='bankintegration',
            name='exchange_rate_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when exchange rate was applied', null=True),
        ),
        migrations.AddField(
            model_name='bankintegration',
            name='transaction_currency',
            field=models.CharField(blank=True, help_text='Currency code for this transaction (e.g., USD, MYR)', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='converted_amount_in_base_currency',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted to tenant base currency', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Exchange rate used for conversion (from transaction_currency to base_currency)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='exchange_rate_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when exchange rate was applied', null=True),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='transaction_currency',
            field=models.CharField(blank=True, help_text='Currency code for this transaction (e.g., USD, MYR)', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='converted_amount_in_base_currency',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted to tenant base currency', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Exchange rate used for conversion (from transaction_currency to base_currency)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='exchange_rate_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when exchange rate was applied', null=True),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='transaction_currency',
            field=models.CharField(blank=True, help_text='Currency code for this transaction (e.g., USD, MYR)', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='importexportjob',
            name='converted_amount_in_base_currency',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted to tenant base currency', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='importexportjob',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Exchange rate used for conversion (from transaction_currency to base_currency)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='importexportjob',
            name='exchange_rate_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when exchange rate was applied', null=True),
        ),
        migrations.AddField(
            model_name='importexportjob',
            name='transaction_currency',
            field=models.CharField(blank=True, help_text='Currency code for this transaction (e.g., USD, MYR)', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='plaidconnection',
            name='converted_amount_in_base_currency',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted to tenant base currency', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='plaidconnection',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Exchange rate used for conversion (from transaction_currency to base_currency)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='plaidconnection',
            name='exchange_rate_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when exchange rate was applied', null=True),
        ),
        migrations.AddField(
            model_name='plaidconnection',
            name='transaction_currency',
            field=models.CharField(blank=True, help_text='Currency code for this transaction (e.g., USD, MYR)', max_length=3, null=True),
        ),
    ]
