# Generated by Django 5.2.6 on 2025-12-23 08:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=255)),
                ('compliance_type', models.CharField(choices=[('audit_trail', 'Audit Trail'), ('user_activity', 'User Activity'), ('data_access', 'Data Access Log'), ('gdpr', 'GDPR Compliance'), ('sox', 'SOX Compliance'), ('pci_dss', 'PCI DSS'), ('hipaa', 'HIPAA'), ('other', 'Other')], max_length=50)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('completed', 'Completed'), ('reviewed', 'Reviewed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_reports', to='tenants.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_compliance_reports', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_reports', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Compliance Report',
                'verbose_name_plural': 'Compliance Reports',
                'db_table': 'compliance_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=255)),
                ('tax_period_start', models.DateField()),
                ('tax_period_end', models.DateField()),
                ('tax_type', models.CharField(choices=[('income_tax', 'Income Tax'), ('sales_tax', 'Sales Tax'), ('vat', 'VAT'), ('gst', 'GST'), ('withholding_tax', 'Withholding Tax'), ('property_tax', 'Property Tax'), ('other', 'Other')], max_length=50)),
                ('tax_jurisdiction', models.CharField(blank=True, max_length=100)),
                ('total_taxable_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_tax_liability', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_tax_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('completed', 'Completed'), ('filed', 'Filed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_reports', to='tenants.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_reports', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tax Report',
                'verbose_name_plural': 'Tax Reports',
                'db_table': 'tax_reports',
                'ordering': ['-tax_period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON'), ('xml', 'XML')], max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('compliance_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='reporting.compliancereport')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='reporting.report')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_exports', to='tenants.tenant')),
                ('tax_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='reporting.taxreport')),
            ],
            options={
                'verbose_name': 'Report Export',
                'verbose_name_plural': 'Report Exports',
                'db_table': 'report_exports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportingSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('default_date_format', models.CharField(default='YYYY-MM-DD', max_length=20)),
                ('default_export_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', max_length=20)),
                ('auto_generate_reports', models.BooleanField(default=False)),
                ('report_retention_days', models.IntegerField(default=365)),
                ('enable_report_caching', models.BooleanField(default=True)),
                ('cache_expiry_hours', models.IntegerField(default=24)),
                ('enable_email_notifications', models.BooleanField(default=True)),
                ('default_recipients', models.JSONField(blank=True, default=list)),
                ('max_export_file_size_mb', models.IntegerField(default=100)),
                ('allowed_export_formats', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporting_settings', to='tenants.company')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_settings', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Reporting Settings',
                'verbose_name_plural': 'Reporting Settings',
                'db_table': 'reporting_settings',
                'unique_together': {('tenant', 'company')},
            },
        ),
    ]
