# Generated by Django 5.2.6 on 2025-12-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='billing_cycle',
            field=models.CharField(choices=[('trial', 'Trial'), ('monthly', 'Monthly'), ('annual', 'Annual')], default='trial', help_text='Billing cycle', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, help_text='ISO 3166-1 alpha-2 country code', max_length=2),
        ),
        migrations.AddField(
            model_name='tenant',
            name='currency_code',
            field=models.CharField(default='USD', help_text='ISO 4217 currency code', max_length=3),
        ),
        migrations.AddField(
            model_name='tenant',
            name='domain_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('active', 'Active')], default='pending', help_text='Domain verification status', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='industry_code',
            field=models.CharField(blank=True, db_index=True, help_text='Industry classification code', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='onboarded_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when onboarding was completed', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='onboarding_status',
            field=models.CharField(choices=[('INCOMPLETE', 'Incomplete'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], db_index=True, default='INCOMPLETE', help_text='Onboarding completion status', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='plan_code',
            field=models.CharField(blank=True, help_text='Subscription plan code', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='primary_domain',
            field=models.CharField(blank=True, help_text='Primary custom domain or subdomain', max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_id',
            field=models.CharField(blank=True, help_text='External subscription ID', max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='supports_einvoice',
            field=models.BooleanField(default=False, help_text='E-invoicing enabled'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='supports_inventory',
            field=models.BooleanField(default=False, help_text='Inventory management enabled'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='supports_multi_branch',
            field=models.BooleanField(default=False, help_text='Multi-branch support enabled'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='supports_tax',
            field=models.BooleanField(default=False, help_text='Tax compliance enabled'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='timezone',
            field=models.CharField(default='UTC', help_text='IANA timezone identifier', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='trial_expiry',
            field=models.DateTimeField(blank=True, help_text='Trial expiration date', null=True),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['onboarding_status'], name='tenants_onboarding_status_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['country_code', 'industry_code'], name='tenants_country_industry_idx'),
        ),
    ]
