# Generated by Django 5.2.6 on 2025-12-25 09:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_add_onboarding_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantOnboardingProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_step', models.IntegerField(default=1, help_text='Current step number (1-5)')),
                ('completed_steps', models.JSONField(blank=True, default=list, help_text='List of completed step numbers')),
                ('step_data', models.JSONField(blank=True, default=dict, help_text='Data collected in each step')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Onboarding Progress',
                'verbose_name_plural': 'Tenant Onboarding Progresses',
                'db_table': 'tenant_onboarding_progress',
            },
        ),
        migrations.CreateModel(
            name='TenantPreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preset_type', models.CharField(choices=[('chart_of_accounts', 'Chart of Accounts'), ('tax_rates', 'Tax Rates'), ('currency', 'Currency'), ('invoice_numbering', 'Invoice Numbering'), ('einvoice_config', 'E-Invoice Configuration'), ('country_settings', 'Country Settings')], max_length=50)),
                ('payload', models.JSONField(default=dict, help_text='Preset data (JSON)')),
                ('source_country', models.CharField(blank=True, help_text='Country code this preset is for', max_length=2)),
                ('source_industry', models.CharField(blank=True, help_text='Industry code this preset is for', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Preset',
                'verbose_name_plural': 'Tenant Presets',
                'db_table': 'tenant_presets',
                'indexes': [models.Index(fields=['tenant', 'preset_type'], name='tenant_presets_tenant_type_idx')],
                'unique_together': {('tenant', 'preset_type')},
            },
        ),
    ]
