# Generated by Django 5.2.6 on 2025-12-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_add_onboarding_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantonboardingprogress',
            name='preset_progress',
            field=models.JSONField(blank=True, default=dict, help_text='Preset module completion status with record counts and percentages'),
        ),
    ]
