# Generated by Django 4.2.24 on 2025-09-25 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FounderFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('feedback_type', models.CharField(choices=[('feature-request', 'Feature Request'), ('product-feedback', 'Product Feedback'), ('general-feedback', 'General Feedback'), ('partnership', 'Partnership Inquiry'), ('bug-report', 'Bug Report'), ('other', 'Other')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('contact_preference', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('video', 'Video Call'), ('no-preference', 'No Preference')], default='email', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('in-progress', 'In Progress'), ('responded', 'Responded'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_founder_feedback', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='founder_feedback', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Founder Feedback',
                'verbose_name_plural': 'Founder Feedback',
                'db_table': 'founder_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EarlyAccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('ceo', 'CEO/Founder'), ('cfo', 'CFO'), ('accountant', 'Accountant'), ('bookkeeper', 'Bookkeeper'), ('finance-manager', 'Finance Manager'), ('other', 'Other')], max_length=20)),
                ('company_size', models.CharField(choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-1000', '201-1000 employees'), ('1000+', '1000+ employees')], max_length=20)),
                ('industry', models.CharField(choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('consulting', 'Consulting'), ('other', 'Other')], max_length=20)),
                ('current_challenges', models.TextField(help_text="Current financial challenges you're facing")),
                ('timeline', models.CharField(choices=[('immediately', 'Immediately'), ('1-month', 'Within 1 month'), ('3-months', 'Within 3 months'), ('6-months', 'Within 6 months'), ('exploring', 'Just exploring')], max_length=20)),
                ('expectations', models.TextField(blank=True, help_text='What do you expect from early access?', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('interview_scheduled', 'Interview Scheduled'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('onboarded', 'Onboarded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('interview_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_early_access_requests', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='early_access_requests', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Early Access Request',
                'verbose_name_plural': 'Early Access Requests',
                'db_table': 'early_access_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BetaProgramApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('ceo', 'CEO/Founder'), ('cfo', 'CFO'), ('accountant', 'Accountant'), ('bookkeeper', 'Bookkeeper'), ('finance-manager', 'Finance Manager'), ('other', 'Other')], max_length=20)),
                ('company_size', models.CharField(choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-1000', '201-1000 employees'), ('1000+', '1000+ employees')], max_length=20)),
                ('use_case', models.TextField(help_text='How do you plan to use OASYS?')),
                ('expectations', models.TextField(blank=True, help_text='What are your expectations from the beta program?', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('onboarded', 'Onboarded'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_beta_applications', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beta_applications', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Beta Program Application',
                'verbose_name_plural': 'Beta Program Applications',
                'db_table': 'beta_program_applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
