# Generated by Django 5.2.6 on 2025-12-25 08:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_uniq_tenant_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_tier',
            field=models.CharField(choices=[('trial', 'Trial'), ('business', 'Business'), ('enterprise', 'Enterprise')], default='trial', help_text='Account access tier', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('corporate', 'Corporate/Business Account'), ('trial', 'Trial Account'), ('personal', 'Personal Account')], default='corporate', help_text='Type of account', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='corporate_email_verified',
            field=models.BooleanField(default=False, help_text='Corporate email verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Email address verified'),
        ),
        migrations.CreateModel(
            name='AccountConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_account_type', models.CharField(max_length=20)),
                ('to_account_type', models.CharField(default='corporate', max_length=20)),
                ('conversion_reason', models.CharField(blank=True, max_length=255)),
                ('corporate_email', models.EmailField(help_text='Corporate email to convert to', max_length=254)),
                ('verification_token', models.CharField(blank=True, max_length=255, null=True)),
                ('verification_expires', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_conversion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Conversion',
                'verbose_name_plural': 'Account Conversions',
                'db_table': 'account_conversions',
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('linkedin', 'LinkedIn'), ('microsoft', 'Microsoft'), ('facebook', 'Facebook'), ('github', 'GitHub')], max_length=50)),
                ('provider_account_id', models.CharField(help_text='User ID from provider', max_length=255)),
                ('email', models.EmailField(help_text='Email from social provider', max_length=254)),
                ('access_token', models.TextField(blank=True, help_text='OAuth access token (encrypted)')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth refresh token (encrypted)')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Additional provider data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Account',
                'verbose_name_plural': 'Social Accounts',
                'db_table': 'social_accounts',
                'unique_together': {('provider', 'provider_account_id')},
            },
        ),
    ]
