# Generated by Django 5.2.6 on 2025-09-26 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='order_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='salesquote',
            name='quote_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(fields=('tenant', 'order_number'), name='uniq_tenant_order_number'),
        ),
        migrations.AddConstraint(
            model_name='salesquote',
            constraint=models.UniqueConstraint(fields=('tenant', 'quote_number'), name='uniq_tenant_quote_number'),
        ),
    ]
