# Generated by Django 5.2.6 on 2025-09-26 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_salesorder_order_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_order_lines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sales_order_lines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesquoteline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_quote_lines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesquoteline',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sales_quote_lines', to=settings.AUTH_USER_MODEL),
        ),
    ]
