# Generated by Django 5.2.6 on 2025-12-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salescommission_salesopportunity_salessettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='converted_amount_in_base_currency',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted to tenant base currency', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Exchange rate used for conversion (from transaction_currency to base_currency)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='exchange_rate_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when exchange rate was applied', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='transaction_currency',
            field=models.CharField(blank=True, help_text='Currency code for this transaction (e.g., USD, MYR)', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='salescommission',
            name='converted_amount_in_base_currency',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted to tenant base currency', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='salescommission',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Exchange rate used for conversion (from transaction_currency to base_currency)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='salescommission',
            name='exchange_rate_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when exchange rate was applied', null=True),
        ),
        migrations.AddField(
            model_name='salescommission',
            name='transaction_currency',
            field=models.CharField(blank=True, help_text='Currency code for this transaction (e.g., USD, MYR)', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='salesopportunity',
            name='converted_amount_in_base_currency',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted to tenant base currency', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='salesopportunity',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Exchange rate used for conversion (from transaction_currency to base_currency)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='salesopportunity',
            name='exchange_rate_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when exchange rate was applied', null=True),
        ),
        migrations.AddField(
            model_name='salesopportunity',
            name='transaction_currency',
            field=models.CharField(blank=True, help_text='Currency code for this transaction (e.g., USD, MYR)', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='converted_amount_in_base_currency',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted to tenant base currency', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='exchange_rate_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when exchange rate was applied', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='transaction_currency',
            field=models.CharField(blank=True, help_text='Currency code for this transaction (e.g., USD, MYR)', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='salesquote',
            name='converted_amount_in_base_currency',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted to tenant base currency', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='salesquote',
            name='exchange_rate_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when exchange rate was applied', null=True),
        ),
        migrations.AddField(
            model_name='salesquote',
            name='transaction_currency',
            field=models.CharField(blank=True, help_text='Currency code for this transaction (e.g., USD, MYR)', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='converted_amount_in_base_currency',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted to tenant base currency', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Exchange rate used for conversion (from transaction_currency to base_currency)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='exchange_rate_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when exchange rate was applied', null=True),
        ),
        migrations.AddField(
            model_name='salessettings',
            name='transaction_currency',
            field=models.CharField(blank=True, help_text='Currency code for this transaction (e.g., USD, MYR)', max_length=3, null=True),
        ),
    ]
