# Generated by Django 5.2.6 on 2025-12-26 09:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_tenantonboardingprogress_preset_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_currency', models.CharField(default='USD', help_text='Base currency for reporting', max_length=3)),
                ('default_exchange_rate_provider', models.CharField(choices=[('exchangerate-api', 'ExchangeRate-API'), ('fixer', 'Fixer.io'), ('currencylayer', 'CurrencyLayer'), ('openexchangerates', 'OpenExchangeRates')], default='exchangerate-api', max_length=50)),
                ('auto_update_rates', models.BooleanField(default=True, help_text='Automatically update exchange rates')),
                ('update_frequency_hours', models.IntegerField(default=24, help_text='Rate update frequency in hours')),
                ('last_rate_update', models.DateTimeField(blank=True, null=True)),
                ('api_key', models.CharField(blank=True, help_text='API key for rate provider', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='currency_config', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Currency Config',
                'verbose_name_plural': 'Currency Configs',
                'db_table': 'currency_configs',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_currency', models.CharField(help_text='Source currency code (e.g., USD)', max_length=3)),
                ('to_currency', models.CharField(help_text='Target currency code (e.g., EUR)', max_length=3)),
                ('rate', models.DecimalField(decimal_places=8, help_text='Exchange rate', max_digits=18)),
                ('source', models.CharField(choices=[('api', 'API'), ('manual', 'Manual'), ('fixed', 'Fixed Rate')], default='api', max_length=50)),
                ('provider', models.CharField(blank=True, help_text='Rate provider (e.g., exchangerate-api, fixer.io)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'db_table': 'exchange_rates',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('from_amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('to_amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('exchange_rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('conversion_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_conversions', to='tenants.tenant')),
                ('exchange_rate_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fx_conversion.exchangerate')),
            ],
            options={
                'verbose_name': 'Currency Conversion',
                'verbose_name_plural': 'Currency Conversions',
                'db_table': 'currency_conversions',
                'ordering': ['-conversion_date'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='ISO 4217 currency code (e.g., MYR, USD, SGD)', max_length=3)),
                ('name', models.CharField(help_text='Currency name (e.g., Malaysian Ringgit)', max_length=255)),
                ('symbol', models.CharField(blank=True, help_text='Currency symbol (e.g., RM, $)', max_length=10)),
                ('is_base_currency', models.BooleanField(default=False, help_text='Is this the base currency for the tenant?')),
                ('decimal_places', models.IntegerField(default=2, help_text='Number of decimal places')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'db_table': 'currencies',
                'ordering': ['-is_base_currency', 'code'],
                'indexes': [models.Index(fields=['tenant', 'is_base_currency'], name='currencies_tenant__a6e325_idx'), models.Index(fields=['tenant', 'code'], name='currencies_tenant__ea5b34_idx')],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['from_currency', 'to_currency', 'is_active'], name='exchange_ra_from_cu_156c8a_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['last_updated'], name='exchange_ra_last_up_6991c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('tenant', 'from_currency', 'to_currency', 'valid_from')},
        ),
    ]
