# Generated by Django 5.2.6 on 2025-12-23 08:16

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_item_sku'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryValuation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valuation_method', models.CharField(choices=[('fifo', 'FIFO (First In First Out)'), ('lifo', 'LIFO (Last In First Out)'), ('average_cost', 'Average Cost'), ('weighted_average', 'Weighted Average'), ('specific_identification', 'Specific Identification')], default='fifo', max_length=50)),
                ('valuation_date', models.DateField()),
                ('total_inventory_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_items', models.IntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calculated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculated_valuations', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_valuations', to='tenants.company')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_valuations', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Inventory Valuation',
                'verbose_name_plural': 'Inventory Valuations',
                'db_table': 'inventory_valuations',
                'ordering': ['-valuation_date', '-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='InventorySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_valuation_method', models.CharField(choices=[('fifo', 'FIFO (First In First Out)'), ('lifo', 'LIFO (Last In First Out)'), ('average_cost', 'Average Cost'), ('weighted_average', 'Weighted Average'), ('specific_identification', 'Specific Identification')], default='fifo', max_length=50)),
                ('enable_automatic_valuation', models.BooleanField(default=False)),
                ('valuation_currency', models.CharField(default='USD', max_length=3)),
                ('allow_negative_stock', models.BooleanField(default=False)),
                ('enable_low_stock_alerts', models.BooleanField(default=True)),
                ('low_stock_threshold_percentage', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Percentage of min stock level to trigger alert', max_digits=5)),
                ('auto_calculate_reorder_points', models.BooleanField(default=False)),
                ('enable_barcode_scanning', models.BooleanField(default=True)),
                ('barcode_prefix', models.CharField(blank=True, help_text='Prefix for auto-generated barcodes', max_length=20)),
                ('require_barcode', models.BooleanField(default=False)),
                ('enable_multi_warehouse', models.BooleanField(default=True)),
                ('notify_on_low_stock', models.BooleanField(default=True)),
                ('notify_on_reorder_point', models.BooleanField(default=True)),
                ('notify_on_negative_stock', models.BooleanField(default=True)),
                ('default_export_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('json', 'JSON')], default='csv', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_settings', to='tenants.company')),
                ('default_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_settings', to='inventory.warehouse')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_settings', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Inventory Settings',
                'verbose_name_plural': 'Inventory Settings',
                'db_table': 'inventory_settings',
                'unique_together': {('tenant', 'company')},
            },
        ),
    ]
