# Generated by Django 5.2.6 on 2025-12-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0006_add_e_invoice_submission'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='einvoicesubmission',
            new_name='e_invoice_s_invoice_d1d296_idx',
            old_name='e_invoice__invoice_8a3f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='einvoicesubmission',
            new_name='e_invoice_s_tenant__8cda0f_idx',
            old_name='e_invoice__tenant__b4c5e6_idx',
        ),
        migrations.RenameIndex(
            model_name='einvoicesubmission',
            new_name='e_invoice_s_status_30562a_idx',
            old_name='e_invoice__status_7d8e9f_idx',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='e_invoice_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20, null=True),
        ),
    ]
