# Generated by Django 5.2.6 on 2025-12-26 06:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0008_digitalcertificate_invoicecompliancerule_and_more'),
        ('tenants', '0004_tenantonboardingprogress_preset_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrate',
            name='code',
            field=models.CharField(help_text='Tax code (legacy field, use tax_code FK)', max_length=50),
        ),
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Tax code (e.g., GST_STANDARD, SST_SALES)', max_length=50)),
                ('name', models.CharField(help_text='Tax code name (e.g., GST Standard Rate)', max_length=255)),
                ('tax_type', models.CharField(choices=[('sales', 'Sales Tax'), ('vat', 'VAT'), ('gst', 'GST'), ('service', 'Service Tax'), ('excise', 'Excise Tax'), ('custom', 'Custom Tax')], help_text='Type of tax', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False, help_text='System-defined codes cannot be deleted')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_codes', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tax Code',
                'verbose_name_plural': 'Tax Codes',
                'db_table': 'tax_codes',
                'ordering': ['code'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.AddField(
            model_name='taxrate',
            name='tax_code',
            field=models.ForeignKey(blank=True, help_text='Tax code (FK to TaxCode)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_rates', to='invoicing.taxcode'),
        ),
    ]
