# Generated by Django 5.2.6 on 2025-09-26 13:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('data_classification', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted'), ('top_secret', 'Top Secret')], default='confidential', help_text='Data classification level', max_length=20)),
                ('requires_audit', models.BooleanField(default=True)),
                ('retention_period_days', models.PositiveIntegerField(default=2555)),
                ('is_sensitive', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement_date', models.DateField()),
                ('statement_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('book_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reconciled_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bank Reconciliation',
                'verbose_name_plural': 'Bank Reconciliations',
                'db_table': 'bank_reconciliations',
                'ordering': ['-statement_date'],
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('data_classification', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted'), ('top_secret', 'Top Secret')], default='confidential', help_text='Data classification level', max_length=20)),
                ('requires_audit', models.BooleanField(default=True)),
                ('retention_period_days', models.PositiveIntegerField(default=2555)),
                ('is_sensitive', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('normal_balance', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chart of Account',
                'verbose_name_plural': 'Chart of Accounts',
                'db_table': 'chart_of_accounts',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('data_classification', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted'), ('top_secret', 'Top Secret')], default='confidential', help_text='Data classification level', max_length=20)),
                ('requires_audit', models.BooleanField(default=True)),
                ('retention_period_days', models.PositiveIntegerField(default=2555)),
                ('is_sensitive', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('reference', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('entry_type', models.CharField(choices=[('manual', 'Manual Entry'), ('system', 'System Generated'), ('recurring', 'Recurring Entry'), ('adjustment', 'Adjustment Entry')], default='manual', max_length=50)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'db_table': 'journal_entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Journal Entry Line',
                'verbose_name_plural': 'Journal Entry Lines',
                'db_table': 'journal_entry_lines',
            },
        ),
    ]
