# Generated by Django 5.2.6 on 2025-12-26 06:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_fiscalyear_pettycashaccount_pettycashtransaction_and_more'),
        ('tenants', '0004_tenantonboardingprogress_preset_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccounts',
            name='type',
            field=models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], help_text='Account type (legacy field, use account_type FK)', max_length=50),
        ),
        migrations.CreateModel(
            name='GLAccountType',
            fields=[
                ('data_classification', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted'), ('top_secret', 'Top Secret')], default='confidential', help_text='Data classification level', max_length=20)),
                ('requires_audit', models.BooleanField(default=True)),
                ('retention_period_days', models.PositiveIntegerField(default=2555)),
                ('is_sensitive', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Account type code (e.g., asset, liability)', max_length=50)),
                ('name', models.CharField(help_text='Account type name (e.g., Asset, Liability)', max_length=255)),
                ('normal_balance', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], help_text='Normal balance for this account type', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False, help_text='System-defined types cannot be deleted')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order for display in UI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gl_account_types', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GL Account Type',
                'verbose_name_plural': 'GL Account Types',
                'db_table': 'gl_account_types',
                'ordering': ['display_order', 'name'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='account_type',
            field=models.ForeignKey(blank=True, help_text='Account type (FK to GLAccountType)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounting.glaccounttype'),
        ),
    ]
