# Generated by Django 5.2.6 on 2025-12-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_chartofaccounts_type_glaccounttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='converted_amount_in_base_currency',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted to tenant base currency', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Exchange rate used for conversion (from transaction_currency to base_currency)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='exchange_rate_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when exchange rate was applied', null=True),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='transaction_currency',
            field=models.CharField(blank=True, help_text='Currency code for this transaction (e.g., USD, MYR)', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='converted_amount_in_base_currency',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted to tenant base currency', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Exchange rate used for conversion (from transaction_currency to base_currency)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='exchange_rate_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when exchange rate was applied', null=True),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='transaction_currency',
            field=models.CharField(blank=True, help_text='Currency code for this transaction (e.g., USD, MYR)', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='converted_amount_in_base_currency',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted to tenant base currency', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Exchange rate used for conversion (from transaction_currency to base_currency)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='exchange_rate_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when exchange rate was applied', null=True),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='transaction_currency',
            field=models.CharField(blank=True, help_text='Currency code for this transaction (e.g., USD, MYR)', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='creditdebitnote',
            name='converted_amount_in_base_currency',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted to tenant base currency', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='creditdebitnote',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Exchange rate used for conversion (from transaction_currency to base_currency)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='creditdebitnote',
            name='exchange_rate_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when exchange rate was applied', null=True),
        ),
        migrations.AddField(
            model_name='creditdebitnote',
            name='transaction_currency',
            field=models.CharField(blank=True, help_text='Currency code for this transaction (e.g., USD, MYR)', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='converted_amount_in_base_currency',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted to tenant base currency', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Exchange rate used for conversion (from transaction_currency to base_currency)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='exchange_rate_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when exchange rate was applied', null=True),
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='transaction_currency',
            field=models.CharField(blank=True, help_text='Currency code for this transaction (e.g., USD, MYR)', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='converted_amount_in_base_currency',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted to tenant base currency', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Exchange rate used for conversion (from transaction_currency to base_currency)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='exchange_rate_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when exchange rate was applied', null=True),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='transaction_currency',
            field=models.CharField(blank=True, help_text='Currency code for this transaction (e.g., USD, MYR)', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='glaccounttype',
            name='converted_amount_in_base_currency',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted to tenant base currency', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='glaccounttype',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Exchange rate used for conversion (from transaction_currency to base_currency)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='glaccounttype',
            name='exchange_rate_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when exchange rate was applied', null=True),
        ),
        migrations.AddField(
            model_name='glaccounttype',
            name='transaction_currency',
            field=models.CharField(blank=True, help_text='Currency code for this transaction (e.g., USD, MYR)', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='converted_amount_in_base_currency',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted to tenant base currency', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Exchange rate used for conversion (from transaction_currency to base_currency)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='exchange_rate_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when exchange rate was applied', null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='transaction_currency',
            field=models.CharField(blank=True, help_text='Currency code for this transaction (e.g., USD, MYR)', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='pettycashaccount',
            name='converted_amount_in_base_currency',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted to tenant base currency', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='pettycashaccount',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Exchange rate used for conversion (from transaction_currency to base_currency)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='pettycashaccount',
            name='exchange_rate_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when exchange rate was applied', null=True),
        ),
        migrations.AddField(
            model_name='pettycashaccount',
            name='transaction_currency',
            field=models.CharField(blank=True, help_text='Currency code for this transaction (e.g., USD, MYR)', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='pettycashtransaction',
            name='converted_amount_in_base_currency',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted to tenant base currency', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='pettycashtransaction',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Exchange rate used for conversion (from transaction_currency to base_currency)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='pettycashtransaction',
            name='exchange_rate_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when exchange rate was applied', null=True),
        ),
        migrations.AddField(
            model_name='pettycashtransaction',
            name='transaction_currency',
            field=models.CharField(blank=True, help_text='Currency code for this transaction (e.g., USD, MYR)', max_length=3, null=True),
        ),
    ]
